global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shaili_backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    
  - job_name: 'shaili_model_metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/model/metrics'
    
  - job_name: 'shaili_system_metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/system/metrics'
    
  - job_name: 'shaili_memory_metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/memory/metrics'
    
  - job_name: 'shaili_rag_metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/rag/metrics'

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
