improvement_strategy:
  # Número mínimo de interacciones para considerar mejora
  min_interactions_for_improvement: 50
  
  # Umbral de calidad para iniciar mejora
  improvement_threshold: 0.7
  
  # Frecuencia de actualización en horas
  update_frequency_hours: 24
  
  # Número máximo de micro-ramas a generar por dominio
  max_micro_branches_per_domain: 10
  
  # Configuración de entrenamiento de adapters
  adapter_training:
    # Tamaño del batch
    batch_size: 64
    
    # Número de épocas
    epochs: 5
    
    # Tasa de aprendizaje
    learning_rate: 5e-5
    
    # Dropout para regularización
    dropout: 0.15
  
  # Política de actualización de adapters
  adapter_update_policy:
    # Mantener solo los N mejores adapters
    max_adapters_per_branch: 5
    
    # Umbral de mejora para considerar merge de adapter
    merge_improvement_threshold: 0.08
  
  # Configuración de generación dinámica de ramas
  dynamic_branch_generation:
    # Método de clustering
    clustering_method: "dbscan"
    
    # Número de clusters para generación de micro-ramas
    n_clusters: 5
    
    # Umbral de similitud para crear micro-rama
    similarity_threshold: 0.75
  
  # Métricas de evaluación
  quality_metrics:
    # Pesos para cálculo de puntuación compuesta
    coherence_weight: 0.4
    diversity_weight: 0.3
    factuality_weight: 0.2
    toxicity_penalty: 0.1
  
  # Configuración de expansión de dominios
  domain_expansion:
    # Umbral de coherencia para nuevos dominios
    coherence_threshold: 0.7
    
    # Tamaño mínimo de cluster para crear dominio
    min_cluster_size: 5
    
    # Máximo de nuevos dominios por iteración
    max_new_domains: 3
  
  # Logging
  logging:
    level: "INFO"
    file: "logs/continuous_improvement.log"
    
  # Recursos computacionales
  compute_resources:
    max_gpu_memory: 16  # GB
    max_cpu_cores: 8
    max_ram: 32  # GB
