version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: shaili-postgres-dev
    environment:
      POSTGRES_DB: shaili_db
      POSTGRES_USER: shaili_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-yo}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shaili_user -d shaili_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para caché y colas
  redis:
    image: redis:7-alpine
    container_name: shaili-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-yo}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    name: shaili-dev-network
